### ISSUE TITLE
AssertionError: Error: all query identities do not appear in gallery

### ISSUE THREAD

**Issue by aliencaocao** [tinyvision/SOLIDER-REID#12]
请问这个query文件夹该怎么准备？
我尝试模仿market1501的数据格式准备了我自己的数据。可以成功训练，但是一到validation就报错这个。能请您解释下query这个文件夹里该有什么吗？
![image](https://github.com/tinyvision/SOLIDER-REID/assets/20109683/42d5ae58-bc00-40b3-be6e-e215f14ed3a5)

![image](https://github.com/tinyvision/SOLIDER-REID/assets/20109683/18d50e5a-549b-4ee5-9f3d-e2360dc943f3)
这个是我的训练文件夹

![image](https://github.com/tinyvision/SOLIDER-REID/assets/20109683/bce54488-60d0-40cf-ab56-74e09fe68bfe)
这个是gallery

![image](https://github.com/tinyvision/SOLIDER-REID/assets/20109683/e3347177-1671-427f-a1ed-91b799077d33)
这个是我现在的query，是从gallery中每个class选一个

我的数据只有一个camera id

**Comment by cwhgn** [comment]
query包含的是待查询图片。您换成自己的数据之后，我理解对应的datasets中的文件需要进行一定修改的，您可以根据您报错的问题定位debug下，然后进行下修改。另外，欢迎点赞关注。

**Comment by aliencaocao** [comment]
我这边修改好了，但我有几个问题：
1.我这边有train和val两个gallery，但是query只有一个。都是按照market1501的命名规范命名好的。我是不是可以假设，在运行val期间您的脚本会根据class id只使用没有出现在train的那些class，即使他们都在一个query文件夹内。
2.关于reranking如果gallery有3-4张图片但query只有一个，是不是reranking就没有任何用处了，直接用euclidean就行？

我这边的数据是很多图片，每张图片对应一个想找的人，每张图片会包括2-4个人，我可以把bbox crop出来。这种情况下，是不是需要为每张图片创建一个query和gallery文件夹？
已知每张图片里要找的人有可能重复，这种情况下有可能用re ranking吗？
另外，在不能保证每张图片里一定有要找到人的情况下，您建议该如何？是设定一个distance阈值吗？

感谢您的耐心解答
