### ISSUE TITLE
load pretrained model issue

### ISSUE THREAD

**Issue by Realdr4g0n** [tinyvision/SOLIDER-REID#14]
Hello. Thank you for sharing your research. I have a question regarding the process of loading a pretrained model from the SOLIDER repository. It seems that the model is not being loaded correctly. Is this intentional?

To provide a detailed explanation, in the file SOLIDER-REID/model/make_model.py, on line 193, the model is loaded once through init_model, and then there is an additional loading process if pretrained_choice is set to self. However, in the second load when pretrained_choice is self, not all keys are matched, and nothing is done. Is this the intended code?

I am confused about how to apply this process when training my own dataset. I would greatly appreciate it if you could provide some guidance.

**Comment by cwhgn** [comment]
Thanks for your attention. The pre-trained model is only loaded once, i.e., through SOLIDER-REID/model/make_model.py, on line 193.  "An additional loading process if pretrained_choice is set to self" in your question, do you mean the code in line 228? They are from the original [TransReID repo](https://github.com/damo-cv/TransReID) and not suitable for our case. If your want to use the pretrained model from [SOLIDER](https://github.com/tinyvision/SOLIDER), you should set the pretrained_choice to imagenet. If your want to use the model trained from SOLIDER-REID as init model for resuming, you can follow the steps in [ISSUE#5](https://github.com/tinyvision/SOLIDER-REID/issues/5).

**Comment by Realdr4g0n** [comment]
Oh I think I got confused after seeing [this reply](https://github.com/tinyvision/SOLIDER-REID/issues/2#issuecomment-1503094968).
The task I'm trying to do is to train my dataset with the SOLIDER backbone pretrained on LU Person.

According to [this reply](https://github.com/tinyvision/SOLIDER-REID/issues/2#issuecomment-1503094968), if you want to use the SOLIDER pretrained model, you have to enter the parameter as self. Does the SOLIDER pretrained here mean a fine tuned model like market1501?
As I said before, I only want to load the SOLIDER backbone and fine-tune it by learning from my data.

Thanks again for sharing your great research and I look forward to your reply.

p.s) And the load weight I said is correct to mean the 228 line you said.

**Comment by cwhgn** [comment]
If you want to use the SOLIDER pretrained model, you have to enter the parameter as **imagenet**. **self** is used for the model from SOLIDER-REID repo, not from SOLIDER repo.
