### ISSUE TITLE
Clarification Needed: Running Test on Market1501 Dataset with SWIN Base Model

### ISSUE THREAD

**Issue by lelnazrezaeel** [tinyvision/SOLIDER-REID#16]
Hi there,

I hope this message finds you well. I've been exploring your repository (https://github.com/tinyvision/SOLIDER-REID) and I'm quite impressed with your work on person re-identification using SWIN models.

I'm currently trying to run tests on the Market1501 dataset using the SWIN base model, as mentioned in the run_test.sh file. In this file, there is a reference to the model checkpoint path: ./log/msmt17/swin_base/transformer_120.pth. However, I'm a bit unsure about what exactly I should replace this path with to ensure proper testing on the Market1501 dataset with the SWIN base model.

Could you kindly provide some guidance on what the correct path replacement should be for the transformer_120.pth file when working with the Market1501 dataset and the SWIN base model?

I really appreciate your time and effort in developing this project, and any assistance you could provide would be incredibly valuable to me.

Thank you so much for your help!

**Comment by cwhgn** [comment]
You can download the models from [SOLIDER-ReID repo](https://github.com/tinyvision/SOLIDER-REID/tree/master), and replace the path of './log/msmt17/swin_base/transformer_120.pth' with your saved path of the downloaded models. Then you can run the runtest.sh file for your test.

**Comment by lelnazrezaeel** [comment]
Thank you.
