### ISSUE TITLE
可以导出到onnx和tensorrt吗

### ISSUE THREAD

**Issue by aliencaocao** [tinyvision/SOLIDER-REID#8]
如题

**Comment by cwhgn** [comment]
目前代码暂时没有这个功能，需要的话可以自行添加下。

**Comment by aliencaocao** [comment]
好的谢谢，请问你们有试过这个吗

**Comment by cwhgn** [comment]
目前还没有试过。主要还是偏research的目的，所以目前还未涉及到部署相关内容。如果后面大家需求比较多，我们会考虑加上。感谢关注！

**Comment by aliencaocao** [comment]
好的，我会给予尝试，如果成功了会PR，谢谢回答

**Comment by cwhgn** [comment]
感谢支持！

**Comment by chenscottus** [comment]
Hello,

     Have you done this? Converting to ONNX?

     Thanks!

-Scott

**Comment by chenscottus** [comment]
https://github.com/tinyvision/SOLIDER/issues/9
